### ISSUE TITLE
Not Using Glide Latest Version?

### ISSUE THREAD

**Issue by tabish075** [erikagtierrez/multiple-media-picker#15]
Hi again, this lib is using very old version of Glide.. should use latest of glide .. because in my case there is a conflict between dependencies (NOT WORKING) i am using glide 4.x.x for some other stuff 
Thanks.

**Comment by PandaMonkey** [comment]
Hi @tabish075  , Could you show your pom file? I am interested in such version conflict problems. Maybe I can help you identify the finer granularity root cause. Then, solve the problem in another way. If you concern the privacy problem, you can also send it to my e-mail: pandamonkey1@sina.com

**Comment by ghost** [comment]
Hi, 

I am also facing same issue. can you please tell us how we can use the latest Glide library.

**Comment by erikagtierrez** [comment]
Can you please try with the new version 1.0.5 ? 😄
