### ISSUE TITLE
Slow when entering the gallery activity 

### ISSUE THREAD

**Issue by LtotheWT** [erikagtierrez/multiple-media-picker#18]
I have experience 3 seconds delay when entering the gallery class. Probably due to load the content. 
May i know any ways to reduce the delay ?
Thanks for this library, appreciate it. :)

**Comment by erikagtierrez** [comment]
Hmmm, can you give me more details on it? Because it seems weird to me. I've tried with heavy galleries and I can't reproduce your situation!
