### ISSUE TITLE
Unable to use your library

### ISSUE THREAD

**Issue by anthonyhow** [erikagtierrez/multiple-media-picker#25]
After I implement your library, the below error showed up

`Program type already present: android.support.v4.app.BackStackRecord$Op
Message{kind=ERROR, text=Program type already present: android.support.v4.app.BackStackRecord$Op, sources=[Unknown source file], tool name=Optional.of(D8)}`

Is there any solution to this?

**Comment by erikagtierrez** [comment]
Can you please try with the new version 1.0.5 ? 😄
