### ISSUE TITLE
unable to install dependency. Throwing error during gradle build

### ISSUE THREAD

**Issue by sanjay147654** [erikagtierrez/multiple-media-picker#36]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugManifest'.

Caused by: java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs

Iam getting this error. Can you please help?

**Comment by ibrahim-iqbal** [comment]
Your manifest file has issues in it
