### ISSUE TITLE
Crash when selecting multiple Videos form different folders

### ISSUE THREAD

**Issue by Gwindor-Aut** [erikagtierrez/multiple-media-picker#7]
First of all, thank you for this great library, it saved me a lot of time!

Now to my problem, every time, I select a video, switch to an other folder and it crashes with this Error: https://pastebin.com/HqyTUm0a

Haven't changed a thing (just added 3 log messages) but I can send you this one class if you really need it.

Version: 1.0.1
Android: 7.0
Device: Samsung A3 2016

**Comment by erikagtierrez** [comment]
Hey! I'm testing it out right now! But I think it might be because I haven't changed the dependency in the readme, it should be: 
compile 'com.erikagtierrez.multiple_media_picker:multiple-media-picker:1.0.2'

Let me know if it works for you!

**Comment by erikagtierrez** [comment]
I dit test it out, and I'm not facing that issue so I really think it might be the version in your case. @Gwindor-Aut

**Comment by Gwindor-Aut** [comment]
Ok, thank you, I'll test it on our project.

**Comment by Gwindor-Aut** [comment]
It works, thank you!
