### ISSUE TITLE
Change the color of text in the title

### ISSUE THREAD

**Issue by aloklearning** [erikagtierrez/multiple-media-picker#9]
Since I'm using the white color as my primaryColor and primaryColorDark so I need the text to be in the black color in the title. Is there any way to do the same? Thanks

**Comment by erikagtierrez** [comment]
Hey! 😁 
I uploaded the version **1.0.3** where you can specify in your colors.xml the title color and the tab title colors as well
```xml
    <color name="titleTextColor">#000000</color>
    <color name="titleTabColor">#000000</color>
    <color name="titleSelectedTabColor">#E040FB</color>
```
